version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: sloth_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: sloth_app
        depends_on:
            - sloth

    sloth:
        image: postgres:16
        restart: always
        volumes:
            - ./tmp/pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: sloth
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        container_name: sloth
